# Generated by Django 4.1.7 on 2023-05-30 13:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('bleague_id', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='bleague_id')),
                ('name', models.CharField(default='default name', max_length=50)),
                ('location', models.CharField(default='unknown', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('district_id', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='bleague_analysis.district')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bleague_id', models.CharField(max_length=50)),
                ('name', models.CharField(default='name', max_length=50)),
                ('number', models.IntegerField(default=0)),
                ('position_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bleague_analysis.team')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('own_score', models.IntegerField(default=999)),
                ('other_score', models.IntegerField(default=999)),
                ('win_or_lose', models.IntegerField(default=999)),
                ('home_or_away', models.IntegerField(default=999)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('other_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_team', to='bleague_analysis.team')),
                ('own_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_team', to='bleague_analysis.team')),
            ],
        ),
    ]
