# Generated by Django 4.1.7 on 2023-03-24 14:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bleague_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bleague_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='bleague_id'),
        ),
        migrations.AddField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at'),
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='default name', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bleague_id', models.CharField(max_length=50)),
                ('name', models.CharField(default='name', max_length=50)),
                ('number', models.IntegerField(default=0)),
                ('position_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bleague_analysis.team')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('own_score', models.IntegerField(default=999)),
                ('other_score', models.IntegerField(default=999)),
                ('win_or_lose', models.IntegerField(default=999)),
                ('home_or_away', models.IntegerField(default=999)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('other_team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_team', to='bleague_analysis.team')),
                ('own_team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_team', to='bleague_analysis.team')),
            ],
        ),
    ]
