# Generated by Django 4.1.7 on 2023-03-24 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bleague_analysis', '0003_team_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='other_team_id',
            new_name='other_team',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='own_team_id',
            new_name='own_team',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='team_id',
            new_name='team',
        ),
    ]
