# Generated by Django 4.1.7 on 2023-03-25 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bleague_analysis', '0005_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='district_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='bleague_analysis.district'),
        ),
    ]
